
on:
    push:
        paths:
            - "package.json"
        branches:
            - "main"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Get version from package.json
        id: lookupVersion
        run: echo "VERSION=$(jq -r '"v" + .version' package.json)" >> $GITHUB_OUTPUT
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          prerelease: false
          generateReleaseNotes: true
          commit: 'main'
          tag: ${{ steps.lookupVersion.outputs.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}